### ISSUE TITLE
Bug: Does not support Prettier 3

### ISSUE THREAD

**Issue by austinw-fineart** [jsverse/transloco-keys-manager#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

No

### Current behavior

`Failed to run prettier prettier.resolveConfig.sync is not a function`
This function was removed as of Prettier 3.0
https://prettier.io/blog/2023/07/05/3.0.0.html

### Expected behavior

https://github.com/ngneat/transloco-keys-manager/issues/79

### Please provide a link to a minimal reproduction of the bug

N/A

### Please provide the environment you discovered this bug in

```markdown
Transloco: 5.0.7
Transloco Keys Manager: 3.8.0
Angular: 16.2.10
Node: 18.18.0
Package Manager: npm 10.2.1
OS: Windows 11 (22H2)
```

### I would like to make a pull request for this bug

No

**Comment by bartholomej** [comment]
Just for the record: This issue is resolved because the repository uses the current prettier 3.2+

BUT just make sure you don't have the older "@ngneat/transloco-keys-manager" package installed at the same time, then you might get this error.

Solution: 
1. Remove `@ngneat/transloco-keys-manager` completely
2. Migrate all imports to `@jsverse/transloco-keys-manager` (including marker and other stuff)

**Comment by shaharkazaz** [comment]
@bartholomej Thanks,  it's probably ok starting from v4.

**Comment by KingDarBoja** [comment]
Still issue is still showing even if using latest version (5.0.0) as the prettier `resolveConfig` function is being called at [run-prettier.ts](https://github.com/jsverse/transloco-keys-manager/blob/022e815c56e76349fffb3c4013691a5ecf35f5ac/src/keys-builder/utils/run-prettier.ts) file.

**Comment by shaharkazaz** [comment]
@KingDarBoja Thanks for sharing! would you like to open a PR and document this somehow? maybe a Q&A section as many use nx

**Comment by KingDarBoja** [comment]
> @KingDarBoja Thanks for sharing! would you like to open a PR and document this somehow? maybe a Q&A section as many use nx

Sounds good, I will see what I can do just in case :)
